services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:9.0.0
    container_name: elasticsearch-dev
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Seguridad básica habilitada
    ports:
      - "9200:9200"  # Exponemos Elasticsearch localmente
    networks:
      - elastic-net

  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.0
    container_name: kibana-dev
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"  # Kibana en el puerto estándar
    networks:
      - elastic-net

volumes:
  es_data:

networks:
  elastic-net:
    driver: bridge