version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch-dev
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g  # Menos memoria para desarrollo
      - ELASTIC_PASSWORD=admin  # Cambia esto para pruebas
      - xpack.security.enabled=true  # Seguridad básica habilitada
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"  # Exponemos Elasticsearch localmente
    networks:
      - elastic-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana-dev
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=admin  # Debe coincidir con la de arriba
    ports:
      - "5601:5601"  # Kibana en el puerto estándar
    networks:
      - elastic-net

volumes:
  es_data:

networks:
  elastic-net:
    driver: bridge